# suppress inspection "UnusedProperty" for whole file
#Sat Dec 28 13:44:53 CET 2024
micronaut:
  application:
    name: "list"
  server:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - http://localhost:5173 # Vite's default dev server port
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization

logging:
  level:
    io.micronaut.http.server.cors: DEBUG